"""add accuracy score to chat history

Revision ID: 024544953f40
Revises: 46a1019098fe
Create Date: 2026-06-08 02:45:36.429913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024544953f40'
down_revision: Union[str, Sequence[str], None] = '46a1019098fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('overall_accuracy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'overall_accuracy')
    # ### end Alembic commands ###
