"""add category to documents

Revision ID: ef1281841ec3
Revises: 024544953f40
Create Date: 2026-06-11 02:55:36.424146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1281841ec3'
down_revision: Union[str, Sequence[str], None] = '024544953f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('total_chunks', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('documents', sa.Column('category', sa.String(), nullable=False, server_default='general'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'category')
    op.drop_column('documents', 'total_chunks')
    # ### end Alembic commands ###
