FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.migrate.txt .
RUN pip install --no-cache-dir -r requirements.migrate.txt

COPY . .

CMD ["alembic", "upgrade", "head"]
